name: Nix-Darwin GC Bug Reproduction

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-nix-darwin-gc:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [good]
    
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        source-url: https://install.lix.systems/lix/lix-installer-aarch64-darwin
    - name: Build Darwin Configuration
      run: |
        nix build .#darwinConfigurations.good.system
        ./result/sw/bin/darwin-rebuild check --flake .#good
