name: Nix-Darwin GC Bug Reproduction

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-nix-darwin-gc:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [bad, good]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          accept-flake-config = true

    - name: Show initial /etc/ contents
      run: |
        echo "=== Initial /etc/ contents ==="
        ls -la /etc/ || true
        echo "=== End initial /etc/ contents ==="

    - name: Install nix-darwin
      run: |
        echo "Installing nix-darwin..."
        sudo nix run nix-darwin -- switch --flake .#${{ matrix.config }}
        echo "nix-darwin installation completed"

    - name: Show /etc/ contents after nix-darwin installation
      run: |
        echo "=== /etc/ contents after nix-darwin installation ==="
        ls -la /etc/ || true
        echo "=== End /etc/ contents after installation ==="

    - name: Show nix-darwin generation info
      run: |
        echo "=== Current nix-darwin generation ==="
        darwin-rebuild --list-generations || true
        echo "=== End generation info ==="

    - name: Run nix-collect-garbage
      run: |
        echo "Running nix-collect-garbage..."
        nix-collect-garbage -d
        echo "Garbage collection completed"

    - name: Show /etc/ contents after garbage collection
      run: |
        echo "=== /etc/ contents after garbage collection ==="
        ls -la /etc/ || true
        echo "=== End /etc/ contents after GC ==="
